name: qpcr_explorer

channels:
  - defaults
  - plotly
  
dependencies:
  - python=3.10
  - plotly-orca==1.2.1
  - pip
  - pip:
    - streamlit==1.21.0
    - plotly==5.13.1
    - psutil==5.9.4
    - requests